### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by Martronic-SA** [eea/eea.facetednavigation#109]
The form layout (with center left and right columns) is not responsive and doesn't show up properly on mobiles.

**Comment by martior** [comment]
Is this on the near term roadmap?

**Comment by alecghica** [comment]
@martior nope. Feel free to contribute on this issue if you need it and we will release it on pypi asap once we have a stable commit.

**Comment by davisagli** [comment]
In case it helps at all, see https://www.mountaineers.org/explore/activities/ for an installation that has been styled to be responsive.

**Comment by avoinea** [comment]
Or the EEA integration https://www.eea.europa.eu/publications

**Comment by avoinea** [comment]
This should be fixed with the latest release.
