### ISSUE TITLE
usePloneDateFormat doesn't work when it is set via configuration import

### ISSUE THREAD

**Issue by cedricmessiant** [eea/eea.facetednavigation#112]
It seems that the daterange criterion usePloneDateFormat works fine when I set it via the configure view but if I export the xml and reimport it, it doesn't work (Plone 4, eea.facetednavigation 9.7).

I think that the issue is due to the fact that the exported xml value is "1" but the code checks that `this.usePloneFormat == "True"`. I'm not sure where to fix it though (in the export or in the widget code)

**Comment by gbastien** [comment]
Hi @cedricmessiant 

funny, I had the same problem recently and finished solving it into the template...

https://github.com/eea/eea.facetednavigation/commit/10ce1dceb58f8d2f2fb0a4e5709658be19159fde

++

Gauthier

**Comment by cedricmessiant** [comment]
Thanks @gbastien !
I forgot to mention that replacing "1" with "True" in the xml solves the issue.

**Comment by cedricmessiant** [comment]
@gbastien it does not...

**Comment by gbastien** [comment]
@cedricmessiant, when there is a value, it considers it "True"...

There is probably a way to solve it in the GS part, but I saw that the management in the template was already done for other cases so I did it there even if it was not the most pretty solution...

**Comment by avoinea** [comment]
Fixed by #86
