### ISSUE TITLE
Release Plone 5 compatible version

### ISSUE THREAD

**Issue by tomgross** [eea/eea.facetednavigation#113]
What's the state of the Plone 5 compatible version?

**Comment by avoinea** [comment]
The release is blocked by #101

**Comment by pbauer** [comment]
Could we at least make a beta-release? I've not made any progress regarding the bug #101. But since the issue only appears when restarting or configuring I don't think it prevents us from using it in production.

**Comment by avoinea** [comment]
@pbauer Should it be a beta release, or a release candidate? Like 10.0rc1

**Comment by pbauer** [comment]
@avoinea A rc1 would get more people to use it and encourage them to hunt for the source of #101 😉 but a beta would probably be more correct. Do as you see fit.

**Comment by avoinea** [comment]
There we go ;) https://pypi.python.org/pypi/eea.facetednavigation#rc1-2016-10-12
