### ISSUE TITLE
Batch not working on Plone 5

### ISSUE THREAD

**Issue by Martronic-SA** [eea/eea.facetednavigation#114]
When you click on a page in batch navigation, you always get the first page.
The problem is that the request url is:
@@faceted_query?b_start%5B%5D=40&version=0efb47f17f1f466fcada64f5f7925879
there is a [] just after the b_start parameter.
I've found that this is coming from that part of the view.js javascript

`  get: function(){
    var hash = jQuery.bbq.getState();
    console.debug(hash);
    var query = {};
    var types = ["number", "boolean", "string"];
    jQuery.each(hash, function(key, value){
      var value_type = typeof(value);
      if(jQuery.inArray(value_type, types) !== -1){
        value = [value];
      }
      query[key] = value;
    });
    return query;
  },
`
The following lines:
      if(jQuery.inArray(value_type, types) !== -1){
        value = [value];
      }
adds the [ ] around the value which is bad with b_start. I don't really understand the aim of doing that.

If you comment those three lines, the batching work as expected.

**Comment by david-batranu** [comment]
I did not manage to reproduce the issue with either Chromium 53 or Firefox 49.0.1. I did however identify a problem with double `b_start` parameters: `b_start[]` from jQuery and `b_start:int` from the server side.

Changing `b_start` to no longer be an `Array` before the `jQuery.get` call removes `b_start[]` and should also fix any batching troubles.
