### ISSUE TITLE
No faceted menu actions when installing eea.facetednavigation 10.0

### ISSUE THREAD

**Issue by ginetsl** [eea/eea.facetednavigation#117]
I was so exciting to see the release of v10.0 with Plone5 full support yesterday! Congrats!!
So I went ahead and tried it. Sadly, it didn't work for me, the menu actions for enabling faceted navigation don't show up. There was no upgrade button available on the plone control panel in my case, btw.

Plone = 5.0.6
eea.facetednavigation = 10.0
eea.faceted.vocabularies = 6.0
eea.jquery = 9.3

Before yesterday I was testing 10.0.dev0 from the git repo, but even after deleting it from my src folder, the actions are a no-show. 
I wonder if there is a setup import step (or several) that didn't get run? I don't see the actions in the zmi's portal_actions neither.

Would love to have it working! Any suggestion?

Thanks,

Ginet

**Comment by avoinea** [comment]
Hi Ginet. This issue doesn't reproduce on our side. Maybe this [short demo video](https://youtu.be/q26w7U83kzM) will help you identify the missing part within your setup.
