### ISSUE TITLE
Plone Portlet Widget

### ISSUE THREAD

**Issue by glimmung** [eea/eea.facetednavigation#119]
I'd like to use a Plone Portlet widget, but the input is "Path to portlet macro" which is new to me. Can someone clue me in as to how to work out what that value is for a given macro (it will be a simple static text portlet containing guidance for the user, FWIW). I see a very elderly question on StackOverlflow about this, so perhaps an example in the widget would be helpful.

**Comment by avoinea** [comment]
This widget refers to the [Old style Classic Plone Portlets](http://docs.plone.org/working-with-content/portlet-management/portlet-types.html?highlight=classic%20portlets#classic). 

If you want to show left/right Plone portlets columns, just use `Enable left/right portlets` with `Faceted settings`
