### ISSUE TITLE
Boolean widget not displaying

### ISSUE THREAD

**Issue by jihaisse** [eea/eea.facetednavigation#120]
When you add a boolean widget (one simple checkbox), the widget is not displayed.
The event in eea.facetednavigation.widgets.checkbox.view.js is not fired because the widget doesn't have the __faceted-checkboxes-widget__ class.

So, in eea.facetednavigation.widgets.boolean.widget.pt line 11 add this line :
`css python: css + ' faceted-checkboxes-widget';`

**Comment by avoinea** [comment]
@jihaisse what version of eea.facetednavigation/Plone are you on?

I can't replicate the issue on **Plone 5** with **eea.facetenavigation 10.0** (see `Is default page?` within screenshot)

![screenshot_20170120_170613](https://cloud.githubusercontent.com/assets/323385/22154103/e3cf681c-df32-11e6-8ed2-d7384f660208.png)

**Comment by avoinea** [comment]
And **Plone4**

![plone4](https://cloud.githubusercontent.com/assets/323385/22154311/af6e4b0a-df33-11e6-88ae-a9cd8f2d9549.png)

**Comment by avoinea** [comment]
Fixed also on **plone4** branch. See release [9.10](https://pypi.python.org/pypi/eea.facetednavigation/9.10#id1)

Keep in mind that version 10.0 is also compatible with Plone 4 and it comes with upgrade steps from 9.x. Still, **don't upgrade to version 10.0** directly in production :)
