### ISSUE TITLE
Homepage Link on pypi is outdatet

### ISSUE THREAD

**Issue by svx** [eea/eea.facetednavigation#124]
Currently the `Homepage Link' on pypi is outdated, it says:  Home Page: http://plone.org/products/eea.facetednavigation  which links to: https://plone.org/download

**Comment by alecghica** [comment]
Fixed in https://github.com/collective/eea.facetednavigation/commit/3ab96ec5ea3bd68dbdf96eb25aafc78b43f6dd88.

**Comment by alecghica** [comment]
Just for the reference, PyPi updated see [eea.facetednavigation](https://pypi.python.org/pypi/eea.facetednavigation/9.12).
