### ISSUE TITLE
Incorrect href in pagination links

### ISSUE THREAD

**Issue by fulv** [eea/eea.facetednavigation#128]
Plone 4.3.4.1
eea.facetednavigation 10.1
plone.app.contenttypes 1.1b2

The pagination links have hrefs of this form:

```
http://site.com/reports/@@faceted_query?version=4ed2420a7405652b13261d364b669091&b_start:int=720
```

This URL loads only the `<dl>` of the results and the `<div class="listingBar">` in the page body, with an empty `<head>`.  As a result, the listing is totally unstyled HTML, and is missing everything else around it.

Compare to this URL, which works for the second page of results:

```
http://site.com/reports#version=4ed2420a7405652b13261d364b669091&b_start=20
```

There are two differences:

1. The `@@faceted_query?` view, versus the `#` fragment format.
2. The `:int` in the `b_start` query string argument.

This is regardless of whether Diazo is on or off, or which layout is used.

**Comment by avoinea** [comment]
Seems deprecated as I can't replicate. Closing.
