### ISSUE TITLE
Do I need a contributor's agreement to contribute here?

### ISSUE THREAD

**Issue by idgserpro** [eea/eea.facetednavigation#140]
We're used to do some PR's to `collective` namespace, but can't do it in `plone` because we don't have a contributor's agreement. We would like to know if a contributor's agreement is needed here or if we can just do a PR.

@mauritsvanrees can you help us here?

**Comment by avoinea** [comment]
> Is the collective one just to make it easier for people already with permission in the repository to create branches?

@idgserpro Yes. 

See also our [CONTRIBUTING.md](https://github.com/eea/eea.facetednavigation/blob/master/CONTRIBUTING.md) guidelines.

**Comment by idgserpro** [comment]
So no contributor's agreement is needed then. Thanks!
