### ISSUE TITLE
Add possibility to set a title on "no selected sorting method" value

### ISSUE THREAD

**Issue by gbastien** [eea/eea.facetednavigation#150]
Hi @alecghica @avoinea 

when using the sorting dropdown, there is an auto added option empty "", meaning that no sorting is done and that relevance sorting is done.  The problem is that as this first option of the drop down select does not have a value (nothing is displayed in the dropdown), users do not understand that relevance sorting is done and they select another sorting that is not the best thing.

So I would like this auto added option to get a value "Relevance" instead emtpy so it is clear.

What do you think?  For now there is no way at all to add a value to this as the extra option is added directly into widget.pt...  So I would at least add a translatable content that could be translated to "" by default if you want to keep backward compat but let developers translate it to something else, like "Relevance"...  Or we translate it to "Relevance" by default, that seem better to me.

Also, there is no way to remove this value as it is added without condition in widget.pt...  But that is something else ;-)

Thank you for advice, I will propose a PR corresponding to what we decide.

Gauthier

**Comment by avoinea** [comment]
@gbastien 
Replacing:

https://github.com/eea/eea.facetednavigation/blob/bff18e725f5cffce182adfee89e1640d5771fde5/eea/facetednavigation/widgets/sorting/widget.pt#L29

with:

```HTML
<option value="" i18n:translate="">Relevance</option>
```
seems to me the easiest and best solution here. Thus, please go for it and add a PR. 

> Also, there is no way to remove this value as it is added without condition in widget.pt... But that is something else ;-)

Indeed, would be nice to have a enable/disable configuration option here ;)

Thank you!

**Comment by gbastien** [comment]
Hi @avoinea 

thank you for feedback, what should be default behavior, translated to "Relevance" or to "" (backward compatible but unhelpful to the user to me...).

I will propose another PR for second "problem", as we do not want to hide it for now, this is not urgent for us ;-)  But adding an option to the widget seem correct to me.

Gauthier

**Comment by avoinea** [comment]
PR is now on release pipeline https://github.com/eea/eea.facetednavigation/pull/155

@gbastien Please do further PR to the develop branch ;)

**Comment by gbastien** [comment]
@avoinea 

right, so changes must be done to the develop branch and you/jenkins/... is taking care of keeping master updated?

Gauthier

**Comment by avoinea** [comment]
indeed!
