### ISSUE TITLE
Set FADE_SPEED to 'fast' by default

### ISSUE THREAD

**Issue by gbastien** [eea/eea.facetednavigation#153]
Hi @avoinea @alecghica 

the navigation accross pages (when using navigation previous/next results) can feel too slow most of times, not really because of Plone but because of the FADE_SPEED parameter that is set to 600ms.  The jQuery default value is 400ms.  Setting FADE_SPEED='fast' signify 200ms and that is what we set in our installations.

I think this should be changed to the default jQuery behavior at least (400ms) and even made configurable (but where?) so user may define the value.

Thank you!

Gauthier

**Comment by avoinea** [comment]
@gbastien Indeed, we should do that. I think it is there from the time when effects were in fancy :)
