### ISSUE TITLE
Make it easy to override the spinner image

### ISSUE THREAD

**Issue by gbastien** [eea/eea.facetednavigation#154]
Hi @avoinea 

is there a way to easily override the spinner image?  For now I think it is necessary to override the entire images folder as it is a resource static folder but then you need to take every contained images...

That would be interesting to define the spinner name in Faceted.Options.SPINNER_NAME or so default to "++resource++faceted_images/ajax-loader.gif" so it is overridable.

What do you think?  I will propose a PR regarding this if it is OK.

Gauthier

**Comment by avoinea** [comment]
@gbastien I see there is an option to disable it:`Faceted.Options.SHOW_SPINNER`, but yes, it would be nice to be able to easily override it via CSS. Thus moving it from JS files to CSS one, maybe on `.faceted_loading` class

**Comment by gbastien** [comment]
@avoinea 

ok I will check tomorrow at the sprint if we can use only the CSS and remove it from the JS.

Indeed for now, it is defined in 3 places (2 JS and CSS) ;-)

Gauthier
