### ISSUE TITLE
Display "No results" by default when... no results found

### ISSUE THREAD

**Issue by gbastien** [eea/eea.facetednavigation#163]
Hi @alecghica @avoinea 

With the default view, when no result is returned, nothing at all is displayed, that is somehow confusing for the visitor because he does not know exactly if there was an error or no result...

It would be nice to have a message like "No results." displayed in this case.

Most of time we override the preview-item.pt and it is sufficient but we often have to override the preview-items.pt just to add this.

I know this is some kind of "breaking change" as it would be displayed for everybody using the default view but I think this is necessary to be explicit.

What do you think?

If ok I will propose a simple PR.  Some translated message with the possibility to translate it to an empty string to get back to previous behavior.

Thank you,

Gauthier

**Comment by avoinea** [comment]
Merged.
