### ISSUE TITLE
While importing GS faceted config, allow to purge at the criterion level

### ISSUE THREAD

**Issue by gbastien** [eea/eea.facetednavigation#202]
Hi @avoinea  @alecghica 

when migrating criteria it would be nice to be able to reapply a faceted config XML and purge only one criterion and not the entire criteria configuration.

Dos that sounds right to you to be able to handle `purge="True"`at the `<criterion>` level?

If so I will propose a PR.

Thank you!

Gauthier

**Comment by avoinea** [comment]
@gbastien Sounds good. 

I would still keep the purge at criteria level for backward compatibility. Thus:

1. If you have `<criteria purge="True">` then the old behavior will apply (all `criterions` are erased before import)
2. Otherwise each `<criterion purge="True">` will replace existing ones.

**Comment by gbastien** [comment]
@avoinea 

yes sure still useful at the `<criteria>` level, just need to define it at the `<criterion>` level.

Actually we apply a little XML file just redefining one single `<criterion>` and leaving others untouched.

I will propose a PR soon.

Thank you for follow up!

Gauthier

**Comment by gbastien** [comment]
Hi @avoinea 

working on this issue and adding tests to `exportimport.txt`, I could not make doctest fail, even when writing wrong things!

Looking at the doctest setup, it is due to the `checker=Py23DocChecker()` defined in `test_doctests.py` while configuring the `exportimport.txt` doctest.

You may test, if you remove the `checker=Py23DocChecker()` and run `bin/test --test exportimport.txt`, you have failing tests.

So I think that may be the case with other doctests as well...

So I do not know why this is failing and how to fix this...

Gauthier

**Comment by gbastien** [comment]
OK, this is due to https://github.com/eea/eea.facetednavigation/blob/master/eea/facetednavigation/tests/test_doctests.py#L25

It should be
`got = re.sub("u'(.*?)'", "'\\1'", got)`
and not 
`got = re.sub("u'(.*?)'", "'\\1'", want)`

I will propose a separated PR...

**Comment by gbastien** [comment]
Fixed with #205
