### ISSUE TITLE
"Results per page" widget only works when setting the default per page to 10. Otherwise paginations will not appear on the page view.

### ISSUE THREAD

**Issue by FarooqAlaulddin** [eea/eea.facetednavigation#222]
I am trying to activate "Result per page" widget on a folder with lot of content. I want the user to be able to select how many results per page they can see. 

The settings:
![image](https://user-images.githubusercontent.com/37892823/128470416-7a6724e8-a220-4c5d-98d0-7191abea633a.png)
 

- The issue that I am having is whenever I try to change the default 10 to anything else. The paginations on the page would disappear and everything on that folder would be returned. 
-  I can not change the 10 results per page, If I do, It would break the limit.
- Using eea.facetednavigation 14.6

**Comment by avoinea** [comment]
@FarooqAlaulddin Can't reproduce it:

![CPT2108061210-1822x734](https://user-images.githubusercontent.com/323385/128487216-48b81eed-fc1d-4963-8804-97a7c97e6afe.gif)

Can you please try it on a fresh Plone instance and make sure is a bug in eea.facetednavigation or another add-on:

```
docker run -it --rm -p 8080:8080 -e ADDONS=eea.facetednavigation plone fg
```

**Comment by FarooqAlaulddin** [comment]
how do i run eea.facetednavigation in a dubg mode without docker?

`sudo bin/plonectl fg client1 <ADDONS=eea.facetednavigation>`?

**Comment by FarooqAlaulddin** [comment]
Resolved. Issue was in:
../buildout-cache/eggs/plone.batching-1.1.6-py3.8.egg/plone/batching/utils.py
