### ISSUE TITLE
Display rich text value on a collection ?

### ISSUE THREAD

**Issue by laulaz** [eea/eea.facetednavigation#230]
On Plone collections, you have a rich text field.
But when faceted is activated, this text is not displayed anywhere.

We would like to display this rich text value below description & before search filters on faceted view.

Would you be OK for such a pull request (in `view.pt`) ?

**Comment by avoinea** [comment]
@laulaz I think so. Even if someone may want it bellow search filters :thinking: 

Can't you accomplish this with a viewlet?

**Comment by laulaz** [comment]
@avoinea I am working on this & have a question for you.

If you want to be able to choose between the text position (above vs below search filters) with a viewlet, it seems to me that it is pretty complex : I will need to split template into viewlets to be able to reorder them. Or declare 2 viewlets managers (one above, one below) to be able to show / hide the one you don't need.

Template code: 
```
      <div id="center-content-area" class="faceted-area center-content-area">
        <!-- Center top -->
        <div tal:define="position string:center" id="center-top-area" class="faceted-area center-top-area">
          <metal:position use-macro="here/@@faceted_macros/macros/position" />
        </div>

        [the text may come here]

        <!-- Content -->
        <metal:results use-macro="here/@@faceted_macros/macros/results" />

        <!-- Center bottom -->
```

Don't you think that a simple "Primary text field" widget would be simplest?  so that the user can decide if:
 1. he wants the text on this faceted search --> non sitewide settings
 2. where he wants it to appear (top / left / right / ...) --> more flexibility

The drawbacks I can see are:
 1. that the usage of this widget may look like the usage of the "text" widget
 2. that integrators may need some CSS to make the text look good if they want it above all other widgets

Conclusion: maybe we could add a setting on the "text" widget to tell it to fetch the content primary text field and not the user input text ...

What do you think ?

**Comment by laulaz** [comment]
@avoinea oh yes we can ...

If so, no need to have a viewlet right ?   this would simplify the implementation for us 😉   and give the responsibility to the integrator / site developer to move things around.

**Comment by avoinea** [comment]
@laulaz Yap.
