### ISSUE TITLE
Update for Plone 6

### ISSUE THREAD

**Issue by pbauer** [eea/eea.facetednavigation#231]
eea.facetednavigation needs some work to work properly with Plone 6 after the old resource-registry was dropped. 
 
* remove py2 and archetypes support
* simplify profiles (keep only default and uninstall)
* remove resource registrations from `registry.xml`, only keep bundles  
* add a webpack-setup similar to collective.collectionfilter or plone.app.imagecropping to build bundles from the js- and css-files
* include js-dependencies in the webpack-setup using module-federation:
  * drop dependency on collective.js.jqueryui. Instead use https://www.npmjs.com/package/jquery-ui
  * drop dependency on `eea.jquery`. The plugins (`ajaxfileupload`, `bbq`, `jstree`, `select2uislider`, `tagcloud`, `select2`) should be includes as npm packages or replaced. Select2 is shipped with Plone.
* update the html-markup (of general templates and widget-templates) and css to use bootstrap 5 to work well with the default theme.

**Branches:**
* [ ] [Plone 6 + Bootstrap grid](https://github.com/collective/eea.facetednavigation/tree/plone6)

**Comment by shogunbr** [comment]
Hello.
This import should be fixed for Plone 6 compatibility:
https://github.com/eea/eea.facetednavigation/blob/29f8a9c1ab44bc32a0a166f0778ecf10a6b7c44d/eea/facetednavigation/interfaces.py#L3

**Comment by avoinea** [comment]
@shogunbr See https://github.com/collective/eea.facetednavigation/tree/plone6 for the current work-in-progress Plone 6 compatibile version.

**Comment by pbauer** [comment]
Our first tests show that it works great but we'll test some more next week. Thanks for the work!

**Comment by krissik** [comment]
I`m testing 16.0a1 for Plone 6.0.4 and noticed that deselecting a filter (clicking the little "x") at "Current Search" widget is not working - see screenshot

![facetednav-unselect-filter](https://github.com/eea/eea.facetednavigation/assets/5301889/e6781360-1091-429a-9c8d-adb8ef4d4d2f)

**Comment by avoinea** [comment]
Released 16.0 - https://pypi.org/project/eea.facetednavigation/16.0/

The remaining issues will be fixed in 16.1+

**Comment by Gomez** [comment]
Closing. All known issues solved with v16.2
