### ISSUE TITLE
Bug: Checkbox Widget with non-ascii characters such as Ü does not work

### ISSUE THREAD

**Issue by jensens** [eea/eea.facetednavigation#25]
I have checkboxes using  vocabulary with a list of cities from a custom catalog index. Works fine as long theres no city such as Nürnberg: Then theres an empty result. 

I wrote it now Nuernberg (which is allowed in german but ugly) to workaround.

I did not test it furthermore, but i expect it to break with any non-ascii character here.

**Comment by avoinea** [comment]
Fixed.
