### ISSUE TITLE
Faceted Navigation has a hard dependency on Archetypes

### ISSUE THREAD

**Issue by squibobblepants** [eea/eea.facetednavigation#27]
The configure_faceted view relies on Archetypes widgets to render, so if for example you have installed plone.app.contenttypes [https://github.com/plone/plone.app.contenttypes] and are using it to make everything a Dexterity content type instead of AT, you get the following stack trace for a folder:

    Traceback (innermost last):
      Module ZPublisher.Publish, line 126, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 46, in call_object
      Module Products.Five.browser.metaconfigure, line 476, in __call__
      Module Products.Five.browser.pagetemplatefile, line 125, in __call__
      Module Products.Five.browser.pagetemplatefile, line 59, in __call__
      Module zope.pagetemplate.pagetemplate, line 132, in pt_render
      Module zope.pagetemplate.pagetemplate, line 240, in __call__
      Module zope.tal.talinterpreter, line 271, in __call__
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 888, in do_useMacro
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 533, in do_optTag_tal
      Module zope.tal.talinterpreter, line 518, in do_optTag
      Module zope.tal.talinterpreter, line 513, in no_tag
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 954, in do_defineSlot
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 533, in do_optTag_tal
      Module zope.tal.talinterpreter, line 518, in do_optTag
      Module zope.tal.talinterpreter, line 513, in no_tag
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 858, in do_defineMacro
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 954, in do_defineSlot
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 533, in do_optTag_tal
      Module zope.tal.talinterpreter, line 518, in do_optTag
      Module zope.tal.talinterpreter, line 513, in no_tag
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 954, in do_defineSlot
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 533, in do_optTag_tal
      Module zope.tal.talinterpreter, line 518, in do_optTag
      Module zope.tal.talinterpreter, line 513, in no_tag
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 946, in do_defineSlot
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 821, in do_loop_tal
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 533, in do_optTag_tal
      Module zope.tal.talinterpreter, line 518, in do_optTag
      Module zope.tal.talinterpreter, line 513, in no_tag
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
      Module zope.tales.tales, line 696, in evaluate
       - URL: /Users/TomB/repositories/plone_coredev/plone.app.contenttypes/src/eea.facetednavigation/eea/facetednavigation/browser/template/configure.pt
       - Line 129, Column 8
       - Expression: <PythonExpr (view.get_schema(criterion))>
       - Names:
          {'args': (),
           'container': <Folder at /site/ibnihb>,
           'context': <Folder at /site/ibnihb>,
           'default': <object object at 0x1002d4b70>,
           'here': <Folder at /site/ibnihb>,
           'loop': {},
           'nothing': None,
           'options': {},
           'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x10871b158>,
           'request': <HTTPRequest, URL=http://localhost:8080/site/ibnihb/configure_faceted.html>,
           'root': <Application at >,
           'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x10876d590>,
           'traverse_subpath': [],
           'user': <PropertiedUser 'admin'>,
           'view': <Products.Five.metaclass.SimpleViewClass from /Users/TomB/repositories/plone_coredev/plone.app.contenttypes/src/eea.facetednavigation/eea/facetednavigation/browser/template/configure.pt object at 0x10a094990>,
           'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x10a094c90>}
      Module zope.tales.pythonexpr, line 59, in __call__
       - __traceback_info__: (view.get_schema(criterion))
      Module <string>, line 1, in <module>
      Module eea.facetednavigation.browser.app.configure, line 331, in get_schema
      Module eea.facetednavigation.browser.app.schema, line 40, in __call__
      Module eea.facetednavigation.widgets.schema, line 23, in __call__
      Module Products.Five.browser.pagetemplatefile, line 125, in __call__
      Module Products.Five.browser.pagetemplatefile, line 59, in __call__
      Module zope.pagetemplate.pagetemplate, line 132, in pt_render
       - Warning: Macro expansion failed
       - Warning: <type 'exceptions.NameError'>: name 'faceted_widget' is not defined
      Module zope.pagetemplate.pagetemplate, line 240, in __call__
      Module zope.tal.talinterpreter, line 271, in __call__
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 858, in do_defineMacro
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 821, in do_loop_tal
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 533, in do_optTag_tal
      Module zope.tal.talinterpreter, line 518, in do_optTag
      Module zope.tal.talinterpreter, line 513, in no_tag
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 821, in do_loop_tal
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 533, in do_optTag_tal
      Module zope.tal.talinterpreter, line 518, in do_optTag
      Module zope.tal.talinterpreter, line 513, in no_tag
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 533, in do_optTag_tal
      Module zope.tal.talinterpreter, line 518, in do_optTag
      Module zope.tal.talinterpreter, line 513, in no_tag
      Module zope.tal.talinterpreter, line 343, in interpret
      Module zope.tal.talinterpreter, line 867, in do_useMacro
      Module zope.tales.tales, line 696, in evaluate
       - URL: /Users/TomB/repositories/plone_coredev/plone.app.contenttypes/src/eea.facetednavigation/eea/facetednavigation/widgets/schema.pt
       - Line 35, Column 8
       - Expression: <PythonExpr (faceted_widget.get_macro(field_id, 'edit'))>
       - Names:
          {'args': (),
           'container': <Folder at /site/ibnihb>,
           'context': <Folder at /site/ibnihb>,
           'default': <object object at 0x1002d4b70>,
           'here': <Folder at /site/ibnihb>,
           'loop': {},
           'nothing': None,
           'options': {},
           'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x108715db8>,
           'request': <HTTPRequest, URL=http://localhost:8080/site/ibnihb/configure_faceted.html>,
           'root': <Application at >,
           'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x108787c90>,
           'traverse_subpath': [],
           'user': <PropertiedUser 'admin'>,
           'view': <eea.facetednavigation.widgets.schema.Schema object at 0x109fba310>,
           'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x109fba550>}
      Module zope.tales.pythonexpr, line 59, in __call__
       - __traceback_info__: (faceted_widget.get_macro(field_id, 'edit'))
      Module <string>, line 1, in <module>
      Module eea.facetednavigation.widgets.widget, line 102, in get_macro
      Module Products.Archetypes.generator.widget, line 147, in __call__
    AttributeError: Macro widgets/string does not exist for <Folder at ibnihb>

It would be really awesome for this product to be able to support both AT and Dexterity based folders!

**Comment by avoinea** [comment]
Not anymore
