### ISSUE TITLE
Tree View for Path Widget Is Overlapped

### ISSUE THREAD

**Issue by l34marr** [eea/eea.facetednavigation#36]
On Plone 4.2.6, when the tree view is long enough, it will be overlapped by the footer.

![path-widget-tree](https://f.cloud.github.com/assets/56113/1697716/f1d3f2a0-5ef9-11e3-904c-6caebb01fde2.png)

By inspecting element in Chrome, if z-index is append in the style settings, everything seems OK.

```
<div class="tree tree-green" id="jstree_1" style="...">
```

However, I don't know how to fix this in source codes.

**Comment by avoinea** [comment]
Fixed
