### ISSUE TITLE
Search text is blank but is returned after a check box or combo box is selected.

### ISSUE THREAD

**Issue by ivanteoh** [eea/eea.facetednavigation#38]
Here are the steps to reproduce this scenario:
- The facet settings are enable smart facets hiding, and enable facet navigation.
- On the Searching text, enter 'spam' and click 'search' button. The page is refresh and results returns.
- Now, I remove the 'spam' on the Searching text, so the Searching text is blank. Then I change other options, for example gender field combo box, from female to male. Then page is refresh and results returns. 
- The 'spam' still in Searching text and not removed. 

The 'spam' text only can remove by removing the 'children' on the Searching text and click 'search' button. The 'spam' should be remove, when we selecting other options.

**Comment by avoinea** [comment]
Fixed
