### ISSUE TITLE
faceted_edit.css should not managed via portal_css ?

### ISSUE THREAD

**Issue by tdesvenain** [eea/eea.facetednavigation#39]
Adding css with conditions and specific render type (import) makes portal_css generate many css (there is one css generated each time a condition or a render type change)

faceted_edit.css, on most sites, will be loaded just on one page
AFAIC, we'd better load this css dicrectly via a viewlet than using the portal_css

**Comment by avoinea** [comment]
Deprecated. Now we use bundles.
