### ISSUE TITLE
'faceted_query' preset on 'Content folder view' for 'Legacy template mappings' in Caching settings 

### ISSUE THREAD

**Issue by ivanteoh** [eea/eea.facetednavigation#49]
That way, we can control the caching operation for 'faceted_query' based on 'Content folder view' ruleset mappings. As it will solve the IE caching problem. We are having problem that IE 8 - 11 cached 'faceted_query' ajax call, and it affect the facet navigation result.

**Comment by avoinea** [comment]
No response on this issue in the last 2 years. Thus, I'll close it.
