### ISSUE TITLE
<div> position mismatch in eea/facetednavigation/browser/template/widgets.pt

### ISSUE THREAD

**Issue by gbastien** [eea/eea.facetednavigation#50]
Hi,

is there a good reason why the two divs with id "center-area" and id "left-area"  are not in the right order ("center-area" is before "left-area").  From what I see it is because of a "float:right" applied on these ids and the "right-area" div.

Moreover, why are center and left area together?  Would that make sense that I propose a pull request setting everything on the same level (each 3 divs separated) and using "float:left" so it is responsive?

We could obviously customize or use super new things like display:flex; but if it is for legacy or I do not know why, I suppose it is better to make the change in the template itself...

Thank you ;-)

Gauthier

**Comment by avoinea** [comment]
Deprecated, obsolete.
