### ISSUE TITLE
Order for criteria in a query

### ISSUE THREAD

**Issue by marfago** [eea/eea.facetednavigation#61]
In my project we have to filter more than 1M items in zeodb. We have a page with some widgets and we know that one of them is very heavy. Fortunately there are some other widgets (filters) which can reduce the partial resultset and speed up a little the query. Is there any way to define the order in which the filter should be applied in the query?

**Comment by demarant** [comment]
@marfago: the order of filters in the catalog query is defined by the actual order of the filters (aka "facets widgets") in the edit facet criteria.
So if you want a certain predefined filter to be applied before the others you just drag and drop the widget above the others and you "hide" it in case is not meant to be used by end-user.

You can verify the filters order and catalog query by adding a "debug widget". 
Hope this helps.

**Comment by marfago** [comment]
Actually it does not solve the issue. Order of filters in the query and order of widget in the page are not the same. The way the page is built (widget on the left or on the right) should be independent on the way the query is built. And query plan (I mean filters order) is very important for performances.

**Comment by demarant** [comment]
@marfago: i know. The independence you are asking for is not implemented in eea.facetednavigation. it would be nice to have. the only way I know is to change the display order of the widgets.

**Comment by davisagli** [comment]
But the query generated by eea.facetednavigation is executed using the portal catalog, which uses a query plan (at least since Plone 4.1)
