### ISSUE TITLE
Adding custom css/javascript to a custom results preview

### ISSUE THREAD

**Issue by marfago** [eea/eea.facetednavigation#64]
Following the summary.pt example I've created a new view template for showing results. I need to add some custom css's/javascripts by adding a section like this:
```
<metal:block fill-slot="style_slot">
        <link href="....." rel="stylesheet" type="text/css"/>
        <link href="......" rel="stylesheet" type="text/css"/>
    </metal:block>    
  
    <metal:jsslot fill-slot="javascript_head_slot">
        <script type="text/javascript" src="......"></script>                        
        <script type="text/javascript" tal:content="string:
            jQuery(document).ready( function() {
                shopFunction();
            });">
        </script>            
    </metal:jsslot>

  
    <body>
     ...... 
    </body>
```

but it does not work. What am I doing wrong here?
Thank you in advance.

**Comment by avoinea** [comment]
Faceted navigation is using only the **content-core** metal-slot from your template, everything else is ignored. Thus, you can put your CSS within portal_css with a specific condition. Same for JS within portal_javascripts with mention that you can bind Faceted specific events to trigger your code:

```
jQuery(document).ready( function() {
  if(window.Faceted){
    jQuery(Faceted.Events).bind(Faceted.Events.AJAX_QUERY_SUCCESS, function(){
      shopFunction();
    });
  }
});
```

Here is the list of all Faceted specific events: https://github.com/eea/eea.facetednavigation/blob/master/eea/facetednavigation/browser/javascript/view.js#L4
