### ISSUE TITLE
Html stuff in filter description

### ISSUE THREAD

**Issue by marfago** [eea/eea.facetednavigation#66]
When using filter widget and a countable checkbox widget, description in filter widget contains html tags (as text). For instance (sorry for the italian text):

```
[X]Categoria
    [X]Foto Storica <span>(40708)</span>

[X] Remove all   
```

**Comment by alecghica** [comment]
@marfago thx for reporting this. I can confirm the issue.

**Comment by alecghica** [comment]
@marfago we tracked the issue here https://taskman.eionet.europa.eu/issues/26195 but I can't give you a resolution time.

**Comment by marfago** [comment]
Thank you.

**Comment by avoinea** [comment]
Deprecated as it was fixed more than 3 years ago.
