### ISSUE TITLE
Javascript console.log statement breaks text widget in IE

### ISSUE THREAD

**Issue by hannoschulz** [eea/eea.facetednavigation#67]
There is a console.log statement in view.js from text widget. That statement breaks javascript execution in IE if developertools are closed.
I found another one in autocomplete widget (not tested)
https://github.com/eea/eea.facetednavigation/search?utf8=%E2%9C%93&q=console.log

To reproduce add a text field search criteria, index SearchableText and search in currents results.

Thanks
Hanno

**Comment by avoinea** [comment]
@hannoschulz Thank you. 

I removed console.log statements from JS code.
