### ISSUE TITLE
http://eggrepo.eea.europa.eu/simple 404 Not Found

### ISSUE THREAD

**Issue by vangheem** [eea/eea.facetednavigation#68]
I seem to have some buildouts that depend on eea.faceted.tool and they are failing now. You should be uploading all dependent packages to pypi. This is breaking buildouts.

**Comment by demarant** [comment]
@vangheem http://eggrepo.eea.europa.eu/simple/ is up again.

**Comment by avoinea** [comment]
@vangheem now also on pypi https://pypi.python.org/pypi/eea.faceted.tool
