### ISSUE TITLE
Plone 5:  Configuration of the widgets fails due to the plone.protect

### ISSUE THREAD

**Issue by karalics** [eea/eea.facetednavigation#71]
Plone Protect does not allow to make any configuration changes in the configure_faceted.html panel.
It does not happen if you create or add widgets - only if you try to edit.

plone protect raises this error:

    Forbidden: Form authenticator is invalid.

Workaround is 

    export PLONE_CSRF_DISABLED=true

before starting the instance.

**Comment by avoinea** [comment]
Obsolete
