### ISSUE TITLE
Integer inputs with zero value gets initialized as blank

### ISSUE THREAD

**Issue by mauritsvanrees** [eea/eea.facetednavigation#75]
Latest eea.facetednavigation 8.3, on Plone 4.3.7 (but seen on earlier versions too).

- Enable faceted navigation somewhere.
- Go to faceted criteria tab.
- Edit the Results per page widget.
- Save it without changing anything.
- You get a warning with javascript: "Invalid number".
- Go to the display tab and see that the Start input is empty.
- Fill in zero and save successfully.
- Edit again, save without changing anything.
- Same error: invalid number.

The same happens for example in the portal_type widget when you set the maximum items to zero. The first save is fine, but when you edit it again, the field is blank.

The warning is displayed by `validate_integers` in `edit.js`.

So probably this happens for all integer inputs with zero as value.

**Comment by avoinea** [comment]
Doesn't reproduce anymore after migration to z3c.form
