### ISSUE TITLE
The Sorting widget breaks on missing indices

### ISSUE THREAD

**Issue by cewing** [eea/eea.facetednavigation#78]
When an index which belongs to a field returned by the call to `portal_atct` ([`tool.getEnabledFields()`](https://github.com/eea/eea.facetednavigation/blob/master/eea/facetednavigation/widgets/sorting/widget.py#L112)) is not actually present in the `portal_catalog`, the [`criteriaByIndexId`](https://github.com/eea/eea.facetednavigation/blob/master/eea/facetednavigation/widgets/sorting/widget.py#L93) method breaks on attempting to retrieve the index object from `portal_catalog`.

Such a circumstance can arise, for example, if you install `alm.solrindex` which by default deletes text indexes such as `Title` and `Description` and gives over indexing those fields to solr.  The line of code linked above throws a key error which then prevents the widget from rendering at all.

One possible fix is to wrap the lookup in a try...except clause like so:

```python
    def criteriaByIndexId(self, indexId):
        catalog_tool = getToolByName(self.context, 'portal_catalog')
        try:
            indexObj = catalog_tool.Indexes[indexId]
        except KeyError:
            return ()
        #...
```

It seems like, so long as the index is not present in the catalog, there would certainly be no criteria associated with it that would be valid, so returning an empty iterable maintains the contract of the method while protecting against this edge case.

**Comment by avoinea** [comment]
Can you please add a pull request with the working code? 

tnx.

**Comment by avoinea** [comment]
Fixed.
