### ISSUE TITLE
Plone 5 version of eea.facetednavigation

### ISSUE THREAD

**Issue by pbauer** [eea/eea.facetednavigation#80]
Are there any concrete plans to create a version of eea.facetednavigation that is compatible with Plone 5?

**Comment by demarant** [comment]
@pbauer hi. At EEA we have not yet plan to move to Plone 5 ... therefore we don't know when we will migrate to it. In any case it is not in this year plan for sure. Hopefully others, with more urgent needs than us, will be able to do some PR.

**Comment by alecghica** [comment]
@pbauer under collective there is a branch for Plone 5 submitted by @tomgross under [fhnw-plone5](https://github.com/collective/eea.facetednavigation/commits/fhnw-plone5) but I don't know the real status of the work done there as no merge (to master) request was done. We will review, support and merge any community work in this direction if something final will be done/submitted.

I will close this ticket as I consider that the original question was fully answered.

**Comment by tomgross** [comment]
@pbauer We did some experiments with this earlier but dropped it in favor of a angular JS based solution. Main open issues were CSFS protection.
