### ISSUE TITLE
The [X] needs to be replaced with an image with an ALT attribute of "Remove this filter"

### ISSUE THREAD

**Issue by ivanteoh** [eea/eea.facetednavigation#96]
Recently one of our 4.x plone sites was audited for WCAG 2.0 AA. The report came back and mentioned that the [X] needs to be replaced with an image with an ALT attribute of "Remove this filter". [X] does not mean anything for the user that uses screen reader.

**Comment by avoinea** [comment]
Fixed. Will be available in the next release.
