### ISSUE TITLE
Daterange widget date format should be configurable

### ISSUE THREAD

**Issue by laulaz** [eea/eea.facetednavigation#99]
Using hard-coded `yyyy-mm-dd` format is problematic.

I'm working on this improvement.

**Comment by laulaz** [comment]
The date displayed in "Current search" widget is also not localized.

**Comment by laulaz** [comment]
This pull request must still be improved : existing behavior (years before 1900 for example) is not working fine because of `$.datepicker.parseDate` conversion.

**Comment by laulaz** [comment]
The code is now working as before when the user doesn't choose to "Use Plone date format".
This pull request is ready (from my point of view).

**Comment by avoinea** [comment]
@laulaz Merged.

Thank you!

**Comment by avoinea** [comment]
Still, I get this error within logs with old-style default values:

```
2016-05-19 10:44:22 ERROR eea.facetednavigation.widgets.daterange time data '2016-05-05' does not match format '%m/%d/%Y' => Start date: 2016-05-05
Traceback (most recent call last):
  File "/plone/instance/src/eea.facetednavigation/eea/facetednavigation/widgets/daterange/widget.py", line 151, in default
    self.python_date_format))
  File "/usr/local/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2016-05-05' does not match format '%m/%d/%Y'
```

Steps to reproduce:
1. Add widget with 'Reuse...' unselected
2. Add default values for start and end
3. Edit widget and select 'Reuse...'

**Comment by avoinea** [comment]
@laulaz also the tests are failing http://ci.eionet.europa.eu/job/eea.facetednavigation-plone4/140/console

**Comment by laulaz** [comment]
I fixed the bug and the tests in https://github.com/collective/eea.facetednavigation/commit/f645e77d008c85450debbd0cd4070331dc45967c

About the error you get when changing the date format (when there is already a value), we should convert the old default value to the new selected format right ?  I don't know how to catch that format must be changed (other than uggly try excepts). Do you have an idea ?

**Comment by avoinea** [comment]
The issue doesn't reproduce anymore.

**Comment by avoinea** [comment]
Ops, it's still there.
